{'name': 'Payment Split',
'summary': Markup('<p>Test Commit Done</p>'),
'sequence': 1,
'price': 2000.0,
'currency': 'USD',
'description': Markup('<p>Test Commit Done</p>'),
'live_test_url': 'https://youtu.be/-zwE9DhFCmA',
'category': '',
'version': '16.0.0.1',
'author': 'Keypress IT Services',
'website': 'https://www.keypress.co.in',
'depends': ['account', 'payment', 'base'],
'data': ['security/ir.model.access.csv', 'views/amount_view_spt.xml', 'views/payment_split_view_spt.xml', 'views/account_move_view.xml', 'views/account_journal_view.xml'],
'application': True,
'installable': True,
'auto_install': False,
'images': ['static/description/Banner.png'],}